language: java

#We build against the latest JDK
jdk:
  - oraclejdk8

#We build at Ubuntu 14.04 (Trusty Thar) as we want to use a more recent Ubuntu version
sudo: required
dist: trusty

before_install:
  # This is https://github.com/codacy/codacy-coverage-reporter#install-jpm, but the SSL certificate is expired, therefore we directly do the commands of the install script here
  # This is needed, because we use TypeScript and Java in one project
  # Disabled because of https://github.com/codacy/codacy-coverage-reporter/issues/46
  #- curl -sL https://cdn.rawgit.com/jpm4j/jpm4j.installers/6b3c5176/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  #- java -jar jpm4j.jar -u init
  # - ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
  - mvn resources:resources -pl org.eclipse.winery.repository.configuration

script:
  - mvn package
  # - mvn jacoco:report-aggregate
  - mkdir build
  - mv org.eclipse.winery.cli/target/*.jar build/
  - mv org.eclipse.winery.repository.client/target/*.jar build/
  - mv org.eclipse.winery.repository.rest/target/*.war build/
  - mv org.eclipse.winery.repository.ui/target/*.war build/
  - mv org.eclipse.winery.topologymodeler/target/*.war build/
  - mv org.eclipse.winery.workflowmodeler/target/*.war build/

deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $AWSAccessKeyId
    secret_access_key: $AWSSecretKey
    bucket: builds.opentosca.org
    acl: public_read
    local_dir: "build/"
    upload-dir: "winery/$TRAVIS_BRANCH"
    region: eu-central-1
    on:
      all_branches: true
      condition: $AWSAccessKeyId
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
    skip_cleanup: true
    on:
      branch: mvndeploy
